-- Title: Even Fibonacci numbers
--
-- Problem #: 2
--
-- Description: Each new term in the Fibonacci sequence is generated by 
-- adding the previous two terms. By starting with 1 and 2, the first 10 
-- terms will be:
-- 			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not 
-- exceed four million, find the sum of the even-valued terms.
--
-- Started: 1/15/2013
-- Completed: 1/15/2013
-- Author: epicoxymoron
-- Language: Haskell

-- super-fancy linear-time fibonacci sequence, graciously stolen from the 
-- interwebs
fibs :: [Int]
fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

euler2' :: Int -> Int
euler2' maxFib = sum $ filter even $ takeWhile (< maxFib) fibs

euler2 :: Int
euler2 = euler2' 4000000
